### ISSUE TITLE
Links out? #minor

### ISSUE THREAD

**Issue by dalmaer** [tcmg/adventure-issues#1]
**Game URL**
http://snailsfordinner.com/chrome-dev-summit/#{%22position%22:{%22x%22:226,%22y%22:66}}

When bumping into the Web Almanec person..... I wonder if some users won't know what it is.... not sure if it's worth a link to it so they can see?

**Comment by tcmg** [comment]
Hey Dion,

The dino person who is talking about the web almanac is standing next to the web almanac book which links out to the almanac.

The convention in Adventure is that the dino people usually stand next to a piece of content (computer, game, video, webpage, podcast), similar to how a staff member might stand next to a demo at a real conference. So I'll close this comment unless you have more concenrs.
