### ISSUE TITLE
Out of place game tiles

### ISSUE THREAD

**Issue by rviscomi** [tcmg/adventure-issues#10]
**Game URL**
http://snailsfordinner.com/chrome-dev-summit/#{%22position%22:{%22y%22:39,%22x%22:77}}
http://snailsfordinner.com/chrome-dev-summit/#{%22position%22:{%22y%22:39,%22x%22:62}}
http://snailsfordinner.com/chrome-dev-summit/#{%22position%22:{%22y%22:50,%22x%22:65}}

**Area**
Outside grassy area

**Describe the bug**
Some game tiles appear misaligned with the map, for example:
![image](https://user-images.githubusercontent.com/1120896/98980998-65470600-24eb-11eb-9f47-233c9b373df2.png)

Other tiles seem to be off by 1px: (these edges appear to flicker as I move around)
![image](https://user-images.githubusercontent.com/1120896/98981099-890a4c00-24eb-11eb-96f9-27177afb7c83.png)

Other tiles seem like they're mixing inside with outside:
![image](https://user-images.githubusercontent.com/1120896/98981309-c8d13380-24eb-11eb-9bd9-04bd0f1672dc.png)

**Comment by alankent** [comment]
Ah! I have been seeing this too. I thought it was a feature! ;-). E.g. look at top left and bottom right corners.
http://snailsfordinner.com/chrome-dev-summit/#cG9zaXRpb24veS81Mi94LzI2MA==
![image](https://user-images.githubusercontent.com/5702163/99424035-0f40dc80-28b6-11eb-9a9d-70c8edc22bf6.png)

**Comment by TimvdLippe** [comment]
@tcmg I am still seeing these issues on the current version. Have these fixes been deployed yet?

![Screenshot 2020-12-02 at 11 14 25](https://user-images.githubusercontent.com/5948271/100865675-89b15500-348f-11eb-87d9-2ae731842882.png)
