### ISSUE TITLE
"How Google Search Works" link is broken

### ISSUE THREAD

**Issue by Hexcles** [tcmg/adventure-issues#100]
**Game URL**
https://developer.chrome.com/devsummit/adventure/#cG9zaXRpb24veC8tNC95Lzcz

**Area**
Search

**Describe the bug**
The link points to `https://`

**Comment by ChristofferBech** [comment]
I think every link in the 'Search' area is still blank. Adding @tcmg here

**Comment by tcmg** [comment]
Fixed
