### ISSUE TITLE
Edit badge button doesn't seem to work

### ISSUE THREAD

**Issue by a4sriniv** [tcmg/adventure-issues#105]
**Game URL**
The URL where you discovered the issue, this should contain X and Y coordinates

https://developer.chrome.com/devsummit/adventure/#cG9zaXRpb24veC8xNjYveS83Mg==

**Area**
Where you encountered the problem (e.g. Web Vitals Room, Firebase room)

**Describe the bug**
The edit badge button doesn't seem todo anything?

**To Reproduce**
1. Go to menu
2. Click on 'Edit Badge'

**Expected behavior**
Being able to edit my name.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 87.0.4280.67

**Comment by ChristofferBech** [comment]
This feature is under development. The 'Edit Badge' button doesn't take you anywhere, but is a placeholder at the moment

**Comment by tcmg** [comment]
Duplicate bug. closing this one.
