### ISSUE TITLE
Lit room links are mixed up

### ISSUE THREAD

**Issue by e111077** [tcmg/adventure-issues#108]
**Game URL**

https://developer.chrome.com/devsummit/adventure/#cG9zaXRpb24veC80NC95LzYw

https://developer.chrome.com/devsummit/adventure/#cG9zaXRpb24veC8zNC95LzYw

**Area**
Lit

**What was wrong?**

The links between the two linked machines (lit maze and lit man) are mixed up

**What should it be?**

lit man machine should link to https://litcds2020.dev/lit-man
and lit maze machine should link to https://litcds2020.dev/lit-maze

**Comment by ChristofferBech** [comment]
@tcmg can you look into this?

**Comment by tcmg** [comment]
fixed
