### ISSUE TITLE
Background tiles sometimes look broken

### ISSUE THREAD

**Issue by MattMonasch** [tcmg/adventure-issues#109]
**Game URL**
https://developer.chrome.com/devsummit/adventure/#cG9zaXRpb24veC8zMzEveS83OQ== (331,79)

**Area**
All over

**Describe the bug**
The background tiles ("the floor") don't always look like they're rendering properly. Often, I'll see what looks like upside-down mirrored L shapes of an incorrect color on the background (images attached)

**To Reproduce**
Honestly not sure how to consistently reproduce. I saw them fairly often as I was walking around. The textures would correct themselves and appear elsewhere if I walked around and came back to the same area.

**Expected behavior**
Background tiles should show incorrect colors in the middle of it's tiling.

**Screenshots**
![Screen Shot 2020-12-02 at 12 26 57 PM](https://user-images.githubusercontent.com/1313215/100935518-0ac71700-34a5-11eb-839b-5085b3d69b19.png)
![Screen Shot 2020-12-02 at 12 29 34 PM](https://user-images.githubusercontent.com/1313215/100935530-0e5a9e00-34a5-11eb-855f-ee446bbb125c.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser: Chrome
 - Version: 86.0.4240.198

**Comment by MattMonasch** [comment]
I wonder if this is a bug that shifts a tile layer over. The watercooler is offcenter here

![Screen Shot 2020-12-02 at 1 53 01 PM](https://user-images.githubusercontent.com/1313215/100936113-e28be800-34a5-11eb-9844-997d0d90cba9.png)
![Screen Shot 2020-12-02 at 1 54 08 PM](https://user-images.githubusercontent.com/1313215/100936107-df90f780-34a5-11eb-86fc-f33edaa7cf23.png)

**Comment by ChristofferBech** [comment]
This has now been fixed
