### ISSUE TITLE
"Equip Now" text misaligned when acquiring a new item

### ISSUE THREAD

**Issue by rviscomi** [tcmg/adventure-issues#11]
**Game URL**
http://snailsfordinner.com/chrome-dev-summit/#{%22position%22:{%22y%22:61,%22x%22:111}}

**Area**
Firebase

**Describe the bug**
Misalignment of "Equip Now" button, happens on any "new item" screen

**To Reproduce**
1. Open up a gift box

**Expected behavior**
Text centered within the button

**Screenshots**
![image](https://user-images.githubusercontent.com/1120896/98981641-34b39c00-24ec-11eb-9fc3-96b9eeca1dac.png)

**Comment by tcmg** [comment]
Yep. We're aware of this one. Thanks!
