### ISSUE TITLE
Pan/Tilt/Zoom should handle "no camera" scenario

### ISSUE THREAD

**Issue by hoch** [tcmg/adventure-issues#114]
**Game URL**
cds-ptz.dev

**Area**
Fugu

**Describe the bug**
A note or a message for users who don’t have a camera would be nice.

**To Reproduce**
1. Go to 'cds-ptz.dev' on a machine without a camera.

(Chrome Version 87.0.4280.67, MacOS)

cc: @tomayac

**Comment by tomayac** [comment]
@beaufortfrancois Can you add a note what this demo does? The reporter was confused and thought they could see their camera, but since they didn't have one, assumed the gray area meant it was disabled.

**Comment by beaufortfrancois** [comment]
During the event there will be always be a video stream users can control.

**Comment by tomayac** [comment]
Might still be worth adding a sentence like…
 
```html
<p>
  This demo broadcasts the video stream of a
  <a href="https://en.wikipedia.org/wiki/Pan%E2%80%93tilt%E2%80%93zoom_camera">
    pan/tilt/zoom webcam
  </a>
  in the middle of New York City that you can
  control remotely from the comfort of your browser.
</p>
```

Maybe just in case also have a fallback image that tells the user the camera is currently down, pointing to your local PTZ demo.

**Comment by beaufortfrancois** [comment]
I've updated demo at https://cds-ptz.dev/

**Comment by tomayac** [comment]
Almost there! Could you add `a {color: red}` to the CSS? The contrast is too weak in dark mode and red works universally.

<img width="681" alt="Screen Shot 2020-12-04 at 14 26 09" src="https://user-images.githubusercontent.com/145676/101169077-b6ef3600-363c-11eb-9b7d-c458a78cd9ed.png">

Nit: Add a period after the link.

**Comment by beaufortfrancois** [comment]
Fixed. Thank you!

**Comment by tomayac** [comment]
Perfect, thank you very much! <3

@tcmg, this Issue can be closed.
