### ISSUE TITLE
"bonjour" subtitle for the corkscrew item

### ISSUE THREAD

**Issue by rviscomi** [tcmg/adventure-issues#12]
**Game URL**
http://snailsfordinner.com/chrome-dev-summit/#{%22position%22:{%22y%22:95,%22x%22:76}}

**Area**
Angular

**What was wrong?**
The subtitle of the corkscrew item is "bonjour" which seems unnecessarily stereotypical and could be potentially offensive

**What should it be?**
Something that doesn't play into French stereotypes. Maybe something fun like "Wine not?"

**Comment by tcmg** [comment]
Nice. Changed to "wine not?"
