### ISSUE TITLE
Lit codelab 404 link

### ISSUE THREAD

**Issue by rviscomi** [tcmg/adventure-issues#13]
**Game URL**
http://snailsfordinner.com/chrome-dev-summit/#{%22position%22:{%22y%22:53,%22x%22:78}}

**Area**
Lit

**What was wrong?**
https://codelabs.developers.google.com/codelabs/the-lit-path 404s

**What should it be?**
Not sure

**Comment by tcmg** [comment]
@e111077 I think this is the correct URL but it's just not posted yet.

Elliott can you confirm?

**Comment by e111077** [comment]
Correct!
