### ISSUE TITLE
iFrame not showing content

### ISSUE THREAD

**Issue by jdr130** [tcmg/adventure-issues#14]
**Game URL**
http://snailsfordinner.com/chrome-dev-summit/#{%22position%22:{%22x%22:102,%22y%22:62}}
**Area**
Firebase Room

**Describe the bug**
When I open one of the features (table with a book), an iframe pops up with an error message that firebase.google.com refused to connect. 

**To Reproduce**
1. Go to the Firebase Room
2. Click on the table with the book near the large Firebase logo. 

**Expected behavior**
This should link out to this pathway: Build your [First Web App with Firebase](https://firebase.google.com/learn/pathways/firebase-web)

**Screenshots**

**Desktop (please complete the following information):**
Google Chrome

**Additional context**

**Comment by tcmg** [comment]
Fixed, thanks!
