### ISSUE TITLE
Rename "Cloud Firestore Learning Pathway" 

### ISSUE THREAD

**Issue by jdr130** [tcmg/adventure-issues#15]
**Game URL**
http://snailsfordinner.com/chrome-dev-summit/#{%22position%22:{%22x%22:100,%22y%22:62}}
**Area**
Firebase room

**What was wrong?**
The pop up called this pathway "Cloud Firestore Learning Pathway"

**What should it be?**
It should be called "Build web apps backed by Cloud Firestore"

**Comment by tcmg** [comment]
Fixed. Will be ready in next review. Thanks!
