### ISSUE TITLE
Character in Room using incorrect prompt

### ISSUE THREAD

**Issue by jdr130** [tcmg/adventure-issues#16]
**Game URL**
http://snailsfordinner.com/chrome-dev-summit/#{%22position%22:{%22x%22:100,%22y%22:62}}

**Area**
Firebase room

**What was wrong?**
The character is giving the incorrect prompt for the Cloud Firestore Pathway, currently reference Cloud messaging instead "Did you know Cloud messaging is a great way to re-engage and keep your users informed?" 

**What should it be?**
The prompt should be "Did you know you can efficiently and securely store and sync app data with Cloud Firestore." (open to edits)

**Comment by tcmg** [comment]
Fixed! will be read in the next review. Thanks Jessica!
