### ISSUE TITLE
Change the name of window for Remote Config Restaurant Demo

### ISSUE THREAD

**Issue by jdr130** [tcmg/adventure-issues#17]
**Game URL**
http://snailsfordinner.com/chrome-dev-summit/#{%22position%22:{%22x%22:100,%22y%22:55}}

**Area**
Firebase room 

**What was wrong?**
Title is correct. It currently reads " Remote Config Restaurant Demo"

**What should it be?**
The title should be "Firebase for Web Demo"

**Comment by tcmg** [comment]
Fixed! Will be ready in next review.
