### ISSUE TITLE
iFrame not showing content

### ISSUE THREAD

**Issue by jdr130** [tcmg/adventure-issues#18]
**Game URL**
http://snailsfordinner.com/chrome-dev-summit/#{%22position%22:{%22x%22:109,%22y%22:55}}

**Area**
Firebase room

**Describe the bug**
When I open one of the features (table with a graduation cap), an iframe pops up with an error message that firebase.google.com refused to connect.

**To Reproduce**
1. Go to Firebase room and head to the bottom right
2. Click on table with graduation cap

**Expected behavior**
This should pop up with a link to the Firebase website: https://firebase.google.com/

**Screenshots**

**Desktop (please complete the following information):**
Google Chrome

**Additional context**

**Comment by tcmg** [comment]
Fixed! Sorry there was a bug. It wasn't meant to be an iframe.
