### ISSUE TITLE
Jitsi Logo Padding

### ISSUE THREAD

**Issue by fuentespatrick** [tcmg/adventure-issues#22]
**Game URL**
http://snailsfordinner.com/chrome-dev-summit/#{%22position%22:{%22x%22:268,%22y%22:97}}

**Area**
Chrome OS room

**What was wrong?**
The Jitsi team asked if we could make their logo a tad smaller (to not to touch the edges of the blue circle).

**What should it be?**
Jitsi logo small enough to provide padding between it and the edges of the blue circle.

**Comment by tcmg** [comment]
Fixed, should be in next round of changes!
