### ISSUE TITLE
Invisible objects prevent me from moving where I expect to be able to move in TF.js room

### ISSUE THREAD

**Issue by jasonmayes** [tcmg/adventure-issues#23]
**Game URL**
http://snailsfordinner.com/chrome-dev-summit/#{%22position%22:{%22y%22:83,%22x%22:107}}

**Area**
Try going north from this square above. Nothing is there but you cant go up. Have to go around. There are a few other places like this too - do not know how many in total - they seem random.

**Describe the bug**
When moving around open space in the TensorFlowjs room I find invisible obstacles which I have to move around in order to pass by.

**To Reproduce**
1. Go to http://snailsfordinner.com/chrome-dev-summit/#{%22position%22:{%22y%22:83,%22x%22:107}}
2. Try to go north into the square that has a light grey line on it 
3. See that you cant move and instead you must go left/right and then up.

**Expected behavior**
I expect to be able to move to this location as it is empty.

**Screenshots**
NA the thing is invisible.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome public latest
 - Version Version 86.0.4240.193 (Official Build) (64-bit)

**Additional context**
NA

**Comment by tcmg** [comment]
Fixed, changes will be visible in next deploy/review.
