### ISSUE TITLE
Rearranging the placement of URLs in DevTools room

### ISSUE THREAD

**Issue by jecfish** [tcmg/adventure-issues#25]
**Game URL**
http://snailsfordinner.com/chrome-dev-summit/#{%22position%22:{%22x%22:302,%22y%22:75}}

**Area**
DevTools room

**What was wrong?**
Rearrange the placement of URLs. When user first enters the room, it would be great to show them the What's new docs link follow by other features.

**What should it be?**
Like this image
<img width="806" alt="Screen Shot 2020-11-16 at 8 36 53 AM" src="https://user-images.githubusercontent.com/5917927/99201713-514f1d00-27e7-11eb-9fea-d3ad7e9ec1b0.png">

**Comment by tcmg** [comment]
Fixed, will be in next round of review
