### ISSUE TITLE
Missing DevTools engineering blog link

### ISSUE THREAD

**Issue by jecfish** [tcmg/adventure-issues#26]
**Game URL**
http://snailsfordinner.com/chrome-dev-summit/#{%22position%22:{%22x%22:302,%22y%22:75}}

**Area**
DevTools room

**What was wrong?**
Missing DevTools engineering blog link: https://developers.google.com/web/tools/chrome-devtools/blog

**What should it be?**
Add the link in the area - bottom section with logs, close to Issues tab URL.

**Comment by tcmg** [comment]
Added. Will be visible in final review.
