### ISSUE TITLE
Camera zooms in unexpectedly and UI is offset

### ISSUE THREAD

**Issue by scheib** [tcmg/adventure-issues#28]
**Game URL**
http://snailsfordinner.com/chrome-dev-summit/#cG9zaXRpb24veS82NC94LzIyOA==

**Area**
Everywhere

**Describe the bug**
The game initially showed a rendering that seemed correct.  The camera flickered into a 'zoomed in' state showing about at about 2x or 4x zoom.  This didn't seem to be based on location or controls.  Later the camera zoomed out briefly, and then back in.

While zoomed in the chat bubbles and character UI appear incorrectly scaled and offset.

**To Reproduce**
Erratic reproduction. Just play and it happens sometimes.

**Expected behavior**
Camera remains at a fixed zoom level.

**Screenshots**
![Screenshot 2020-11-17 at 8 42 36 AM](https://user-images.githubusercontent.com/386971/99419532-11546c80-28b1-11eb-917b-88bd56e05b1e.png)
![Screenshot 2020-11-17 at 8 42 33 AM](https://user-images.githubusercontent.com/386971/99419533-11ed0300-28b1-11eb-81c4-177bd63469fa.png)

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser Chrome
 - Version
Chrome	87.0.4280.54 (Official Build) beta (64-bit)
Platform	13505.40.0 (Official Build) beta-channel rammus

**Comment by alankent** [comment]
When I first joined in, I had the same experience as the second screenshot (maybe even further off and smaller). After running around just as I was going to take a screenshot it snapped back to the first image then worked fine after that.

OS: macos
Browser: Chrome
Version 86.0.4240.193 (Official Build) (x86_64)

**Comment by alankent** [comment]
This just started happening for me more frequently. I try to take a screenshot and it pops back to normal. In particular, on mac, I press SHIFT (it stays there), CMD (it stays there), 4 (number 4) to take a screenshot - the 4 makes it snap back to normal. So I cannot get a screenshot! Lol! (Hmmm, maybe I will remove focus from Chrome first next time...)

**Comment by alankent** [comment]
Yes, moving focus to another window then taking screenshot stopped it resetting. I mention this in case it gives a clue to what is triggering the problem. My issue is the same as the original report, it is just certain actions make it reset correctly.
![image](https://user-images.githubusercontent.com/5702163/99430969-dd804380-28be-11eb-8838-216b37df4869.png)
