### ISSUE TITLE
Move Angular intro codelab and video to the entrance of the room

### ISSUE THREAD

**Issue by mgechev** [tcmg/adventure-issues#30]
**Is your feature request related to a problem? Please describe.**

Everything is already functional and looks pretty well! A suggestion I have is to move Angular's codelab and introduction video to the entrance of the room. This would let folks engage with content early on, when the find the space.

**Describe the Idea or Solution you'd like**

Move the content to the following locations:

http://snailsfordinner.com/chrome-dev-summit/#cG9zaXRpb24veS84NS94Lzcz - angular in 100 seconds
http://snailsfordinner.com/chrome-dev-summit/#cG9zaXRpb24veS84NS94Lzc5 - codelab on basics of angular

**Why?**

Increase the level of engagement.

**Comment by tcmg** [comment]
Fixed. Will be visible in a later push.
