### ISSUE TITLE
Can't type 'space'

### ISSUE THREAD

**Issue by scheib** [tcmg/adventure-issues#31]
**To Reproduce**
1. Type into chat "test space"

Expected: See character say "test" then "space" and see "test space" in chat log.
Actual: See character say "test" and see "test" in chat log.

**Screenshots**
![Screenshot 2020-11-17 at 8 50 12 AM](https://user-images.githubusercontent.com/386971/99420436-0e0db080-28b2-11eb-8a93-fdc172cbc365.png)
![Screenshot 2020-11-17 at 8 50 23 AM](https://user-images.githubusercontent.com/386971/99420434-0e0db080-28b2-11eb-93d2-d2792d1bffa0.png)
![Screenshot 2020-11-17 at 8 50 42 AM](https://user-images.githubusercontent.com/386971/99420432-0d751a00-28b2-11eb-9083-c1e760806f91.png)
![Screenshot 2020-11-17 at 8 50 49 AM](https://user-images.githubusercontent.com/386971/99420430-0d751a00-28b2-11eb-92ee-cc4e9c9849e7.png)

**Comment by JamesHollyer** [comment]
I cannot reproduce this issue. Maybe it has been recently fixed.
<img width="352" alt="Screen Shot 2020-11-30 at 3 57 34 PM" src="https://user-images.githubusercontent.com/8672809/100663909-c7857080-330b-11eb-9ac5-1cd9b9db1a63.png">
