### ISSUE TITLE
After walking on water in location 1 cannot get back onto dry land in location 2

### ISSUE THREAD

**Issue by alankent** [tcmg/adventure-issues#37]
**Game URL**
http://snailsfordinner.com/chrome-dev-summit/#cG9zaXRpb24veS8yNy94LzI5NQ==  - left dry land
http://snailsfordinner.com/chrome-dev-summit/#cG9zaXRpb24veS8zNC94LzI0Mw== - cannot get back onto different dry land

**Area**
Not sure where I am!

**Describe the bug**
I started walking on water here: http://snailsfordinner.com/chrome-dev-summit/#cG9zaXRpb24veS8yNy94LzI5NQ==.
After walking around the building, I tried to get back onto dry land here: http://snailsfordinner.com/chrome-dev-summit/#cG9zaXRpb24veS8zNC94LzI0Mw==
It won't let me - seems to be a wall at the sand. Help! I may drown!
(Not sure if bug is ability to walk on water, or inability to get back onto land)

**To Reproduce**
1. Go to http://snailsfordinner.com/chrome-dev-summit/#cG9zaXRpb24veS8yNy94LzI5NQ==
2. Walk down from land into water then left then up towards http://snailsfordinner.com/chrome-dev-summit/#cG9zaXRpb24veS8zNC94LzI0Mw== (another beach)
3. Try to get onto the sand there (cannot - seems to be a wall)

**Expected behavior**
If I am allowed to walk on water, I expect to be able to get back onto the beach.

**Screenshots**
Me entering water
![image](https://user-images.githubusercontent.com/5702163/99426734-609e9b00-28b9-11eb-9bc4-80ad401cb09e.png)

Cannot get back onto land
![image](https://user-images.githubusercontent.com/5702163/99426228-b32b8780-28b8-11eb-987f-e874feb216f9.png)

**Desktop (please complete the following information):**
 - OS: macos
 - Browser chrome
 - Version 86.0.4240.193 (Official Build) (x86_64)

**Comment by alankent** [comment]
Adding here rather than creating a new bug, but there are strange walls in places. For example in this spot I cannot walk up, down, or right. Down I would have thought I can move down at least.
http://snailsfordinner.com/chrome-dev-summit/#cG9zaXRpb24veS8xMDUveC8zMDQ=
![image](https://user-images.githubusercontent.com/5702163/99427071-c8ed7c80-28b9-11eb-82cc-c436d09f5dc2.png)

Also here, when walking in water, there seems to be a hidden object! http://snailsfordinner.com/chrome-dev-summit/#cG9zaXRpb24veS8xMTEveC8yOTU= I cannot move up.
![image](https://user-images.githubusercontent.com/5702163/99427226-00f4bf80-28ba-11eb-939e-7da43b8aa185.png)

**Comment by alankent** [comment]
I am starting to suspect its just the map is not finished? It needs a good solid debug. E.g. I can see an area but I cannot find a way into it. Not sure on purpose. I can walk through some walls to get close. 

E.g. I can walk down to http://snailsfordinner.com/chrome-dev-summit/#cG9zaXRpb24veS82OS94LzQ2 through a wall, but not through the bookcases to get into the area (which appears to be flooded?). I suspect now the map is just not finished, so the walls are in random spots in some places still.

![image](https://user-images.githubusercontent.com/5702163/99428527-9c3a6480-28bb-11eb-951e-b059091d1af1.png)

**Comment by tcmg** [comment]
Yeah. The list of known issues document mentions that the Search area is inaccessible at the moment and yes the map is unfinished :-)
