### ISSUE TITLE
"Equip now" button text for the "Tab key" swag cutting off

### ISSUE THREAD

**Issue by harleenkbatra** [tcmg/adventure-issues#38]
**Game URL**
Lost the URL :(

**Area**
Tab key swag collection point

**Describe the bug**
I've attached a screenshot but when the "Space bar" swag popup opens up, the "Equip now" button text is cuting off

**Screenshots**
![Screenshot 2020-11-17 at 4 47 54 PM - Display 1](https://user-images.githubusercontent.com/30896731/99429300-b007ba00-28ff-11eb-86cc-459beb023e90.png)

**Desktop (please complete the following information):**
 - Browser - Chrome (Stable)

**Comment by tcmg** [comment]
This is already in the list of known issues.
