### ISSUE TITLE
Tensor flow instrument demo never got past "loading" message

### ISSUE THREAD

**Issue by alankent** [tcmg/adventure-issues#39]
**Game URL**
http://snailsfordinner.com/chrome-dev-summit/#cG9zaXRpb24veS85My94LzEwNg==

**Area**
Tensorflow machine learning

**Describe the bug**
I bumped into the instrument in the tensor flow area. It brought up an offer to recording me singing and turn it into an instrument. It never got beyond the "loading" screen for me.

**To Reproduce**
1. Go to http://snailsfordinner.com/chrome-dev-summit/#cG9zaXRpb24veS85My94LzEwNg==
2. Move down to bump into demo
3. Screen will appear with loading message where the microphone is - after a minute it still shows "loading"

**Expected behavior**
I expected to get beyond the loading message and be able to record my voice, as described in the demo description.

**Screenshots**
![image](https://user-images.githubusercontent.com/5702163/99429651-233c0c80-28bd-11eb-9e82-df3cac441cc0.png)

**Desktop (please complete the following information):**
 - OS: macos
 - Browser Chrome
 - Version 86.0.4240.193 (Official Build) (x86_64)

**Comment by tcmg** [comment]
As noted in the list of known issues, the bespoke experience (which is this) is not yet completed.
