### ISSUE TITLE
Chrome OS laptop bump target

### ISSUE THREAD

**Issue by fuentespatrick** [tcmg/adventure-issues#43]
**Game URL**
http://snailsfordinner.com/chrome-dev-summit/#77+977+9Iu+/vSon77+9bu+/ve+/ve+/vSwscG9zaXRpb24veC8yNzQveS85Mw==

**Area**
Chrome OS room

**What was wrong?**
The large laptop bump target isn't active or styled yet. 

**What should it be?**
Something like having "ChromeOS.dev" written out on the screen of the laptop, and bumping into the target would take the person to https://chromeos.dev/

**Comment by tcmg** [comment]
fixed
