### ISSUE TITLE
Bot in lit does not follow inclusive language guidelines

### ISSUE THREAD

**Issue by e111077** [tcmg/adventure-issues#44]
**Game URL**

http://snailsfordinner.com/chrome-dev-summit/#cG9zaXRpb24veC83MC95LzYz

**Area**

Lit room NPC on top far left

**What was wrong?**

NPC does not follow go/inclusive-language guidelines request changing word "crazy"

**What should it be?**

awesome, cool, amazing

**Comment by tcmg** [comment]
Fixed, will be rolled out next week.
