### ISSUE TITLE
Lit room game urls are not correct

### ISSUE THREAD

**Issue by e111077** [tcmg/adventure-issues#45]
**Game URL**

http://snailsfordinner.com/chrome-dev-summit/#cG9zaXRpb24veC83NS95LzYy

**Area**

Lit

**What was wrong?**

* Component 64: Lit Maze
  * has: https://cds2020.lit.dev/lit-man
  * should be: https://litcds2020.dev/lit-maze
* Component 64: Lit Man
  * has: https://cds2020.lit.dev/lit-maze
  * should be: https://litcds2020.dev/lit-man
* Component 64: 2048-bit
  * has: https://cds2020.lit.dev/2048
  * should be: https://litcds2020.dev/2048
* Component 64: Chess
  * has: https://cds2020.lit.dev/chess
  * should be: https://litcds2020.dev/chess

**Comment by tcmg** [comment]
Updated, will be rolled out next week.
