### ISSUE TITLE
Show map of the whole world

### ISSUE THREAD

**Issue by morsssss** [tcmg/adventure-issues#46]
**Is your feature request related to a problem? Please describe.**
This experience is super cool Still, I found myself wandering around the space, without knowing where I could go or where I was headed - because it's so vast.

**Describe the Idea or Solution you'd like**
A miniature map showing the whole world in a corner of the window. If it isn't too tough to code up in a hurry, of course it would be nice if that included a dot showing the user's current location, or a window showing what's on the screen.

**Why?**
This would be a significant boost to my experience, at least - as I'd know what I could find and where to head!

**Comment by dalmaer** [comment]
Very much so. This is on the roadmap!
