### ISSUE TITLE
Change Name of Resource in Firebase Room

### ISSUE THREAD

**Issue by jdr130** [tcmg/adventure-issues#47]
**Game URL**
http://snailsfordinner.com/chrome-dev-summit/#cG9zaXRpb24veC8xMDMveS82Mw==

**Area**
Firebase Room

**What was wrong?**
First table links out Firestore and labeled "Firestore."

**What should it be?**
Please label this pop-up "Cloud Firestore."

**Comment by tcmg** [comment]
Fixed! Will be available in next week's build.
