### ISSUE TITLE
Change the title of a resource in Firebase room

### ISSUE THREAD

**Issue by jdr130** [tcmg/adventure-issues#48]
**Game URL**
http://snailsfordinner.com/chrome-dev-summit/#cG9zaXRpb24veC8xMTAveS81Ng==
**Area**
Firebase Room

**What was wrong?**
This pop-up is called "Firebase First Web App Learning Pathway"

**What should it be?**
This pop up should be labeled "Build your first web app with Firebase"

**Comment by tcmg** [comment]
Fixed! will be in next week's update.
