### ISSUE TITLE
Last minute content addition to Lit room

### ISSUE THREAD

**Issue by e111077** [tcmg/adventure-issues#49]
**Game URL**

The URL where you discovered the issue, this should contain X and Y coordinates

**Area**

Lit Room

**What was wrong?**

Lit team wants a simple webpage link to be added to our room (sorry I know this is last minute lmk if it's not possible)

**What should it be?**

I have already added this to the demo tracker & we don't really need a canned description:

Name: Lit Samples
URL: https://polymerlabs.github.io/lit-samples/

I also added a short description, but tbh it's not really necessary; we'd just like the object link out in the game

**Comment by tcmg** [comment]
Added. Should be in next week's push. thx!
