### ISSUE TITLE
Missing "Angular in 100 Seconds" video

### ISSUE THREAD

**Issue by mgechev** [tcmg/adventure-issues#5]
**Game URL**
The URL where you discovered the issue, this should contain X and Y coordinates

**Area**

Angular room

**What was wrong?**

Missing "Angular in 100 Seconds" video in the beginning of the room.

**What should it be?**

The video is in the "CDS 2020 | Project Hub" spreadsheet.

**Comment by tcmg** [comment]
Added. Will be ready in next review!
