### ISSUE TITLE
Additional bump target for another case study

### ISSUE THREAD

**Issue by fuentespatrick** [tcmg/adventure-issues#50]
**Game URL**
http://snailsfordinner.com/chrome-dev-summit/#77+977+9Iu+/vSon77+9bu+/ve+/ve+/vSwscG9zaXRpb24veC8yNjkveS84Nw==

**Area**
Chrome OS room

**What was wrong?**
We have one additional case study to link to. 

**What should it be?**
Can we add one more of the book-style bump targets for another case study?

**Comment by tcmg** [comment]
Sure Patrick. Can you add it to the project tracker? And share the name of it once you've created it?

**Comment by fuentespatrick** [comment]
I updated the two case study names in the project tracker. Thanks!

**Comment by tcmg** [comment]
Fixed. Should be in future rollout.
