### ISSUE TITLE
Replace TWA with Trusted Web Activity

### ISSUE THREAD

**Issue by andreban** [tcmg/adventure-issues#51]
**Game URL**
http://snailsfordinner.com/chrome-dev-summit/#cG9zaXRpb24veS84Ny94LzI3OQ==

**Area**
Chrome OS

**What was wrong?**

- The text when bumping on the box on the read reads "Developer Case Study for TWAs and PWAs". 
- The PWA / Trusted Web Activity content is in the wrong area?

**What should it be?**
 - Given the developer confusion between TWA and PWA acronyms, we should use "Trusted Web Activity" instead of TWA.
So, the text should read "Developer Case Study for Trusted Web Activites and PWAs". 
 - The PWA / Trusted Web Activity case study should be in the Fugu / PWA area.

**Comment by tcmg** [comment]
Happy to change this to "Trusted Web Activities".

However, on the topic of whether it should be in Fugu vs ChromeOS, please consult with @fuentespatrick and come back to me.

**Comment by fuentespatrick** [comment]
I removed "TWA" from the name in the project tracker in favor of naming the partner directly.
We'd prefer to keep the case studies featured in the Chrome OS room, but feel free to also have them in the Fugu area if that's a direction you'd like to pursue

**Comment by tcmg** [comment]
Got it. I fixed up the names of all the objects in the Chrome OS room and the chromebook has imagery now as well. I think the Chrome OS is finalised. Should be visible in next week's push. thanks all!
