### ISSUE TITLE
Removal of lit-chess

### ISSUE THREAD

**Issue by e111077** [tcmg/adventure-issues#52]
**Game URL**

http://snailsfordinner.com/chrome-dev-summit/#77+977+9Iu+/vSonx77vv73vv70sLHBvc2l0aW9uL3gvNzQveS81OQ==

**Area**

Lit Room

**What was wrong?**

Please remove the lit-chess game as we will not be shipping it.

**Comment by tcmg** [comment]
Elliott, which word from the latin does the removal of chess affect? Is it the "sunt" word?

**Comment by e111077** [comment]
No worries on that front, we will grant the user that word as a freebee for completing their first game.
