### ISSUE TITLE
A blue pump is on walkable tiles

### ISSUE THREAD

**Issue by TimvdLippe** [tcmg/adventure-issues#67]
**Game URL**
https://developer.chrome.com/devsummit/adventure/#cG9zaXRpb24veC8yNS95Lzg0 coordinates 25,84

**Area**
Below the ice cream vendor area

**Describe the bug**
There is a blue pump here that I can walk on

**To Reproduce**
1. Walk on the tile that the blue pump is on

**Expected behavior**
The tile with the blue pump should not be walkable

**Screenshots**
![Screenshot 2020-12-02 at 11 29 21](https://user-images.githubusercontent.com/5948271/100867119-a0f14200-3491-11eb-9ffa-265ac2587bab.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 86

**Additional context**

**Comment by TimvdLippe** [comment]
Another one, in this case a trash can on 165,48:
![Screenshot 2020-12-02 at 11 41 28](https://user-images.githubusercontent.com/5948271/100868275-51137a80-3493-11eb-9308-c7d45af14dd5.png)

**Comment by TimvdLippe** [comment]
The sign on 202,43:
![Screenshot 2020-12-02 at 11 42 35](https://user-images.githubusercontent.com/5948271/100868406-799b7480-3493-11eb-8334-5f57b3ab2534.png)

**Comment by TimvdLippe** [comment]
This time the reverse, where a sprite appears to be missing on 214,27

![Screenshot 2020-12-02 at 11 46 58](https://user-images.githubusercontent.com/5948271/100868842-165e1200-3494-11eb-81c8-06bf2f276553.png)

**Comment by TimvdLippe** [comment]
Contrary to other benches, there are some that you can sit on (all the benches in this area have this behavior). Is that intended or? Coordinates 257,21:

![Screenshot 2020-12-02 at 11 49 44](https://user-images.githubusercontent.com/5948271/100869121-794fa900-3494-11eb-8262-0ebcb09f8877.png)

**Comment by TimvdLippe** [comment]
Reversal situation again, this time with a present that is unreachable (I can't walk left from the tile I am currently on) 288,84:
![Screenshot 2020-12-02 at 11 56 06](https://user-images.githubusercontent.com/5948271/100869735-5c67a580-3495-11eb-8797-9bbf9598bae1.png)

**Comment by TimvdLippe** [comment]
Another bench I can sit on 428,47:
![Screenshot 2020-12-02 at 11 58 20](https://user-images.githubusercontent.com/5948271/100869915-ac466c80-3495-11eb-93d8-f9b9ad3f9775.png)

**Comment by TimvdLippe** [comment]
Bench at 449,49
![Screenshot 2020-12-02 at 12 00 04](https://user-images.githubusercontent.com/5948271/100870064-eadc2700-3495-11eb-91c9-f36ba06e9552.png)

**Comment by TimvdLippe** [comment]
There is a missing blue machine sprite on 392,70 (you can bump into it and it opens a link to a game.

![Screenshot 2020-12-02 at 12 02 29](https://user-images.githubusercontent.com/5948271/100870262-41496580-3496-11eb-9368-b2ea1eee7e81.png)

**Comment by TimvdLippe** [comment]
The blue machine sprite on 414,71 is misplaced 1 tile to the left:
![Screenshot 2020-12-02 at 12 03 18](https://user-images.githubusercontent.com/5948271/100870332-5de59d80-3496-11eb-8fd3-bb115755da3c.png)

**Comment by TimvdLippe** [comment]
Ladder is misplaced 1 tile to the left on 363,104:
![Screenshot 2020-12-02 at 12 05 39](https://user-images.githubusercontent.com/5948271/100870542-b2891880-3496-11eb-9bb5-fa16b553fff5.png)

**Comment by tcmg** [comment]
Yep. That's all the same bug. We've fixed it just recently.
