### ISSUE TITLE
Game maxes out CPU resources, locks up

### ISSUE THREAD

**Issue by rviscomi** [tcmg/adventure-issues#7]
Throughout the game, my laptop is very unhappy and the fan is spinning at max speed. The game will lock up and I'd have to reload the page or kill the tab. Since this seems to be specific to my setup, I'm not sure what diagnostic info would be useful to you. Let me know what else I can share to help.

 - OS: MacOS Catalina 10.15.7
 - Browser: Chrome
 - Version: 86.0.4240.183

**Comment by tcmg** [comment]
Hey Rick

Can you clarify:
- what type of mac you have? (Air, Pro, etc?)
- do you have any Chrome extensions beyond the corp issued ones installed?
- does this issue affect you every time you load the game?
- And does it always take the same amount of time to "lock up"?

**Comment by rviscomi** [comment]
Mac: MacBook Pro
Non-corp extensions:
- Web Vitals
- LastPass
- Lighthouse
- Link to text fragment
- Wappalyzer
Reproducibility: I've just played the game for a few minutes without any issue. Last time it happened almost immediately, so not consistent. Current memory and CPU consumption by the game are at ~250 MB and ~26.4. Let me know if there's any useful info I could gather the next time it happens.

**Comment by rviscomi** [comment]
While reporting https://github.com/tcmg/adventure-issues/issues/11 I left the "New Item" screen up and my laptop fan started spinning. Memory and CPU are about the same as 10 minutes ago but GPU memory is ~450 MB.
