### ISSUE TITLE
Some game tiles are "shifted"

### ISSUE THREAD

**Issue by mmocny** [tcmg/adventure-issues#74]
**Game URL**
https://developer.chrome.com/devsummit/adventure/#cG9zaXRpb24veS8yNi94LzIzNg==

**Area**
Bridge (fishing)

**Describe the bug**
I've found some game tiles that appear to not "fit" well inside environment.  Typically this is just a 1px shimmer with bordering tiles, but on the bridge there is a tile totally shifted.

Not sure if these are easter eggs I haven't figured out yet, or bugs...

**To Reproduce**
1. Go to 'bridge'
2. See error

**Expected behavior**

**Screenshots**

![Uploading Screen Shot 2020-12-02 at 11.23.01 AM.png…]()

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Browser [Chrome]
 - Version [87]

**Comment by mmocny** [comment]
<img width="380" alt="Screen Shot 2020-12-02 at 11 23 01 AM" src="https://user-images.githubusercontent.com/474282/100900805-393af700-3491-11eb-967d-037cebf2de0d.png">

Screenshot take 2

**Comment by mmocny** [comment]
Another, spurious tile?

<img width="312" alt="Screen Shot 2020-12-02 at 11 27 40 AM" src="https://user-images.githubusercontent.com/474282/100901021-6d161c80-3491-11eb-936c-70906a614b2b.png">

**Comment by mmocny** [comment]
<img width="250" alt="Screen Shot 2020-12-02 at 11 28 16 AM" src="https://user-images.githubusercontent.com/474282/100901102-7dc69280-3491-11eb-892c-9411bf530786.png">

I'll stop now :)

**Comment by mmocny** [comment]
...the longer I play, the more it appears to happen.

If I leave an area and return, I appear to get different artifacts.

<img width="795" alt="Screen Shot 2020-12-02 at 11 31 07 AM" src="https://user-images.githubusercontent.com/474282/100901550-f0377280-3491-11eb-8f18-aa3f7f70f558.png">

**Comment by rowan-m** [comment]
![shifted-world-tiles](https://user-images.githubusercontent.com/108052/100944170-99b04f80-34f6-11eb-8886-7834814e7e89.png)

Pixel 5 / Android 11 / Chrome 87

**Comment by tcmg** [comment]
fixed btw
