### ISSUE TITLE
Nit: "Catch alot of fish"

### ISSUE THREAD

**Issue by mmocny** [tcmg/adventure-issues#76]
**Area**
Any fishing spot

**Describe the bug**
Any time you catch a "fish" you get a progress message: "Catch alot of fish".

**Expected behavior**
First, I think maybe it should be "*a lot* of fish"?

Second, it feels weird to catch a bottle or tin can and score a "lot of fish".  Perhaps something like "Good catch while fishing?"  or "Catch a lot while fishing"?  I've so far only caught 1 fish, so they actually feel like the rare exception here.

Who knows.

**Comment by jrobbins** [comment]
I also found that catching any bottle, can, or snail counts as a fish after the first such item.  Also, I think that the first instance of each color of fish does not count, which seems odd.

**Comment by mmocny** [comment]
YOU CAUGHT A SNAIL!?

**Comment by jrobbins** [comment]
Yeah, at least two snails.  The first one was right after I earned the mid-level fishing rod upgrade.  I never got to the high-level rod, so who knows what other things can be gotten.

**Comment by ChristofferBech** [comment]
There is also a legendary Google fish ;) 

In regards to the 'catch alot of fish' this has been fixed
