### ISSUE TITLE
Black shield on 3 correct answers

### ISSUE THREAD

**Issue by mgechev** [tcmg/adventure-issues#77]
**Game URL**

#cG9zaXRpb24veC8zNy95Lzg0

**Area**

Angular

**Describe the bug**

When folks answer 3 questions correctly, they should receive a black shield. Alternatively, if they answer 1-2, they should get the regular Angular shield.

**To Reproduce**
1. Go to the Angular room
2. Talk to the blacksmith and take the challenge
3. Answer 3 questions correctly
4. You'd receive a red shield instead of a black one

**Expected behavior**

**Screenshots**
<img width="206" alt="Screen Shot 2020-12-02 at 6 46 20 PM" src="https://user-images.githubusercontent.com/455023/100903932-20e9cd00-34cf-11eb-8521-b13c1d553457.png">

**Comment by ChristofferBech** [comment]
I'm not sure I understand... should there be 2 different items given to the users depending on how they complete the quiz? Maybe @tcmg can clarify for me

**Comment by mgechev** [comment]
>I'm not sure I understand... should there be 2 different items given to the users depending on how they complete the quiz? Maybe @tcmg can clarify for me

Yes, that's correct - red shield for 1 or 2 correct answers and black shield for 3 correct answer.

**Comment by tcmg** [comment]
Hey Minko, actually I decided each product room should probably only have one swag to get that is tied to the product itself, so we didn't implement the black shield idea.
