### ISSUE TITLE
Adventure signs me in as a visitor even when I sign in as a Googler.

### ISSUE THREAD

**Issue by MarkTechson** [tcmg/adventure-issues#78]
**Game URL**
Not in game

**Area**
Game 

**Describe the bug**
I'm a googler and even with signing in with my creds, I am designated as a visitor

**To Reproduce**
1. Sign in with Google account.

**Expected behavior**
To be designated as a Googler 👍 

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version Version 87.0.4280.67 (Official Build) (x86_64)

**Comment by ChristofferBech** [comment]
I will make sure that everyone with a @ google email will go through the onboarding flow as a Googler. Currently we are listening to some internal data sheets, where you were maybe not signed up to, this will be corrected.
