### ISSUE TITLE
Invisible wall

### ISSUE THREAD

**Issue by jrobbins** [tcmg/adventure-issues#79]
**Game URL**
The URL where you discovered the issue, this should contain X and Y coordinates
https://developer.chrome.com/devsummit/adventure/#cG9zaXRpb24veC8zOTgveS8xMDY=

**Area**
Desert. Just north of 398,106.

**Describe the bug**
It looks like clear sand, but I can't move closer to the water.

**Comment by ChristofferBech** [comment]
Thanks jrobbins. The area in that part of the world was unfinished at the time of you playing there. The world has been redesigned since and will have proper graphics and areas in the next build.
