### ISSUE TITLE
I got under the pier

### ISSUE THREAD

**Issue by jrobbins** [tcmg/adventure-issues#82]
**Game URL**
https://developer.chrome.com/devsummit/adventure/#cG9zaXRpb24veC8zMTQveS8xMDg=

**Area**
End of a pier at 314,108.

**Describe the bug**
When I hopped onto the last square of the pier, the landscape was drawn over my character.

**Screenshots**
https://screenshot.googleplex.com/6226QXZwSeV9fGd

**Comment by ChristofferBech** [comment]
This is now fixed
