### ISSUE TITLE
black square in the labyrinth

### ISSUE THREAD

**Issue by jrobbins** [tcmg/adventure-issues#83]
**Game URL**
https://developer.chrome.com/devsummit/adventure/#cG9zaXRpb24veC8yMDcveS8xMzA=

**Area**
Labyrinth

**Describe the bug**
There's a black square here with a blue stripe.  I assume that it is supposed to look like something else.

**Screenshots**
https://screenshot.googleplex.com/6E7HovFcjGq8G8G

**Comment by ChristofferBech** [comment]
Great find! 

The square is actually supposed to be a golf ball where you can play miniature golf (coming soon).  Will look into why it has a wrong graphics

**Comment by tcmg** [comment]
The texture caching bug again. I'll close this as it's a dupe
