### ISSUE TITLE
NPC says "PLACEHOLDER"

### ISSUE THREAD

**Issue by jrobbins** [tcmg/adventure-issues#85]
**Game URL**
https://developer.chrome.com/devsummit/adventure/#cG9zaXRpb24veC8xOTIveS8xMTM=

**Area**
Near 192,113.

**Describe the bug**
NPC is standing by the water holding a fishing rod.  Bumping into them shows only "PLACEHOLDER" instead of them saying something specific.

**Screenshots**
https://screenshot.googleplex.com/6zoEhqDUs3rDqB9

**Comment by tcmg** [comment]
Fixed.
