### ISSUE TITLE
Welcome screen navigation isn't clear

### ISSUE THREAD

**Issue by jyasskin** [tcmg/adventure-issues#87]
**Game URL**
https://developer.chrome.com/devsummit/adventure/#south

**Area**
The Welcome screen

**To Reproduce**
1. Go to https://developer.chrome.com/devsummit/adventure/#south, log in for the first time.
2. Click the 'Next' button
3. Try to go back to the previous screen

**Expected behavior**
A button to the left of 'next' lets me go back, or the 4 progress dots in the middle of the dialog are clickable to go between screens. The left arrow at the top of the dialog wasn't obviously the way to go back within this dialog.

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser: Google Chrome | 88.0.4324.27

**Comment by tcmg** [comment]
Although dot pagination is a nice part of the UX of iOS's home screen, the majority of games and apps do not implement this level of polish. We simply don't have time to implement this I'm afraid.
