### ISSUE TITLE
Colored text in welcome dialog looks like links

### ISSUE THREAD

**Issue by jyasskin** [tcmg/adventure-issues#88]
**Game URL**
https://developer.chrome.com/devsummit/adventure/#south

**Area**
Welcome screen

**Describe the bug**
"We have reimagined how we experience conferences with our new virtual experimental summit." has "virtual experimental summit" colored blue, but that's the link color, so I expected it to be clickable.

**Comment by tcmg** [comment]
Ahh. This was intended as a form of emphasis. WAI
