### ISSUE TITLE
Lost control of character - camera following another player

### ISSUE THREAD

**Issue by e111077** [tcmg/adventure-issues#9]
**Game URL**
Sorry I don't have this

**Area**
Central area + Lit room

**Describe the bug**
I picked up an item in the Lit room and my teammate had just finished moving in the central atrium and his camera panned over to me picking up the item and he was unable to regain control of his camera. He had to reload

**To Reproduce**

Not sure if we can reproduce this...

1. Player 1 go to the central atrium
2. Player 2, as player 1 just finishes moving, pick up the item at the bottom right of the Lit room

Hopefully this helps!

**Expected behavior**
Camera shouldn't follow another user

**Screenshots**
Sorry, we didn't see this issue template when it happened

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 86

**Comment by erikhoj** [comment]
Haha, very interesting.

Did the unlock animation play for your teammate, or did the camera just pan to you without playing the animation?

**Comment by e111077** [comment]
cc: @dfreedm

**Comment by dfreedm** [comment]
I don't remember seeing an unlock animation on my side, just the camera slow panning to @e111077
