### ISSUE TITLE
Frustrating dead ends

### ISSUE THREAD

**Issue by jyasskin** [tcmg/adventure-issues#91]
**Game URL**
https://developer.chrome.com/devsummit/adventure/#cG9zaXRpb24veC81NC95LzU5

**Area**
Outside the castle?

**What was wrong?**
I walked up the path between two buildings, thinking I'd be able to walk into the buildings, but it was a dead end

**Comment by ChristofferBech** [comment]
The world has been updated and the area now has a function :) 👍
